class_name Enums

enum BlockColor { CORAL, AMBER, LEMON, MINT, SKY, LAVENDER, SPECIAL }

enum PieceType {
	SINGLE,
	DUO, DUO_V,
	TRI_LINE, TRI_LINE_V, TRI_L, TRI_J,
	TET_SQUARE, TET_LINE, TET_LINE_V,
	TET_T, TET_T_UP, TET_T_R, TET_T_L,
	TET_Z, TET_S, TET_Z_V, TET_S_V,
	TET_L, TET_J, TET_L_H, TET_J_H,
	PENT_PLUS, PENT_U, PENT_T, PENT_LINE, PENT_LINE_V,
	PENT_L3, PENT_J3, PENT_L3_R, PENT_J3_R,
	RECT_2x3, SQ_3x3, RECT_3x2,
	PENT_N, PENT_N_R, PENT_N_V, PENT_N_V2
}

enum GameStatus { READY, PLAYING, PAUSED, CLEARING, GAME_OVER }

enum GameMode { CLASSIC, DAILY_CHALLENGE, TIME_ATTACK }
